language: php

php:
  - "7.2"

cache:
  directories:
    - "./vendor"

dist: trusty

before_script:
  - composer install --no-interaction

script:
  - ./vendor/bin/phpunit
  - docker build -t hshs-domxss-scanner .

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  - provider: script
    skip_cleanup: true
    on:
      branch: develop
    script: >-
      docker tag hshs-domxss-scanner siwecos/hshs-domxss-scanner:develop &&
      docker push siwecos/hshs-domxss-scanner:develop
  - provider: script
    skip_cleanup: true
    on:
      branch: master
    script: >-
      docker tag hshs-domxss-scanner siwecos/hshs-domxss-scanner:latest &&
      docker push siwecos/hshs-domxss-scanner:latest
  - provider: script
    skip_cleanup: true
    on:
      tags: true
    script: >-
      docker tag hshs-domxss-scanner siwecos/hshs-domxss-scanner:$TRAVIS_TAG &&
      docker push siwecos/hshs-domxss-scanner:$TRAVIS_TAG
