language: php

php:
  - "7.1"

services:
  - mysql

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

addons:
  apt:
    sources:
      - mysql-5.7-trusty

dist: trusty

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit

  # Set env vars
env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - PROJECT_NAME_PRD=glowing-thunder-215513
    - CLUSTER_NAME_PRD=siwecoscluster
    - CLOUDSDK_COMPUTE_ZONE=europe-west1-b


jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t hshs-domxss-scanner .
      - docker images
      - docker tag hshs-domxss-scanner "$DOCKER_REPO"/hshs-domxss-scanner:"$TRAVIS_BRANCH"
      - docker push "$DOCKER_REPO"/hshs-domxss-scanner:"$TRAVIS_BRANCH"

before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update kubectl

deploy:
  - provider: script
    script: ./deploy-staging.sh
    skip_cleanup: true
    on:
      branch: develop
  - provider: script
    script: ./deploy-master.sh
    skip_cleanup: true
    on:
      branch: master
